apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: jenkins-jenkins
    servicePort: 8080
