apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - vault.lsst.rocks
      secretName: wildcard-lsst-rocks
  rules:
    - host: vault.lsst.rocks
      http:
        paths:
          - path: /
            backend:
              serviceName: vault-vault
              servicePort: 8200
